[book]
title = "TiDB Document Japanese"
authors = [
  "you06",
  "SakuramiRin"
]

[build]
create-missing = false

[preprocess.links]

[output.html]

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
exclude = [
  "mailto:tongmu@pingcap.com",
  "mailto:info@pingcap.com"
]
