name: Build and Deploy

on:
  push:
    branches:    
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: book/html
        BUILD_SCRIPT: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          make
