name: doc-check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        make prepare
    - name: Run build & test
      run: |
        make doc
